language: java
jdk:
  - openjdk8

services:
  - xvfb

before_install:
  - sudo apt update
  - sudo apt install openjfx
  - javac -classpath /opt/apache-tomcat/lib/servlet-api.jar *.java

install: true  
  
script: 
- ant -buildfile Cinefy/build.xml
