language: java
jdk:
  - openjdk8

services:
  - xvfb

before_install:
  - sudo apt update
  - sudo apt install openjfx

install: true  

addons:
    apt:
      packages:
        ant
    sonarcloud:
      organization: bonjon
      token:
        secure: 39189a7b64e32c31837101132874618a74f4bce3

script: 
- ant -buildfile Cinefy/build.xml
- sonar-scanner
